version: "3.7"
services:
  app:
    build:
      args:
        user: supplementbacon
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: awesomeapp
    container_name: awesomeapp-application
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - awesomeNetwork

  db:
    image: mariadb:10.5
    container_name: awesomeapp-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
    networks:
      - awesomeNetwork

  nginx:
    image: nginx:1.17-alpine
    container_name: awesomeapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - awesomeNetwork

networks:
  awesomeNetwork:
    driver: bridge



